export const icons = [
  [
    { id: "L0", img: "/Light/lights01.png" },
    { id: "L1", img: "/Light/lights02.png" },
    { id: "L2", img: "/Light/lights03.png" },
    { id: "L3", img: "/Light/lights04.png" },
    { id: "L4", img: "/Light/lights05.png" },
    { id: "L5", img: "/Light/lights06.png" },
    { id: "L6", img: "/Light/lights07.png" },
    { id: "L7", img: "/Light/lights08.png" },
    { id: "L8", img: "/Light/lights09.png" },
    { id: "L9", img: "/Light/lights10.png" },
    { id: "L10", img: "/Light/lights11.png" },
    { id: "L11", img: "/Light/lights12.png" },
    { id: "L12", img: "/Light/lights13.png" },
    { id: "L13", img: "/Light/lights14.png" },
    { id: "L14", img: "/Light/lights15.png" },
    { id: "L15", img: "/Light/lights16.png" },
    { id: "L16", img: "/Light/lights17.png" },
    { id: "L17", img: "/Light/lights18.png" },
    { id: "L18", img: "/Light/lights19.png" },
    { id: "L19", img: "/Light/lights20.png" },
    { id: "L24", img: "/Light/lights25.png" },
    { id: "L27", img: "/Light/lights28.png" },
    { id: "L28", img: "/Light/lights29.png" },
    { id: "L31", img: "/Light/lights32.png" },
    { id: "L32", img: "/Light/lights33.png" },
    { id: "L33", img: "/Light/lights34.png" },
    { id: "L34", img: "/Light/lights35.png" },
    { id: "L35", img: "/Light/lights36.png" },
    { id: "L36", img: "/Light/lights37.png" },
    { id: "L37", img: "/Light/lights38.png" },
    { id: "L38", img: "/Light/lights39.png" },
    { id: "L39", img: "/Light/lights40.png" },
  ],
  [
    { id: "F0", img: "/Fan/fans01.png" },
    { id: "F1", img: "/Fan/fans02.png" },
    { id: "F2", img: "/Fan/fans03.png" },
    { id: "F3", img: "/Fan/fans04.png" },
    { id: "F4", img: "/Fan/fans05.png" },
    { id: "F5", img: "/Fan/fans06.png" },
    { id: "F6", img: "/Fan/fans07.png" },
    { id: "F7", img: "/Fan/fans08.png" },
    { id: "F8", img: "/Fan/fans09.png" },
    { id: "F9", img: "/Fan/fans10.png" },
    { id: "F10", img: "/Fan/fans11.png" },
    { id: "F11", img: "/Fan/fans12.png" },
    { id: "F12", img: "/Fan/fans13.png" },
    { id: "F13", img: "/Fan/fans14.png" },
    { id: "F14", img: "/Fan/fans15.png" },
    { id: "F15", img: "/Fan/fans16.png" },
    { id: "F16", img: "/Fan/fans17.png" },
    { id: "F17", img: "/Fan/fans18.png" },
    { id: "F18", img: "/Fan/fans19.png" },
    { id: "F19", img: "/Fan/fans20.png" },
  ],
];
