export const variantData = [
  [
    { switches: 2, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 0 },
    { switches: 4, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 0 },
    { switches: 0, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 1 },
    { switches: 0, bells: 0, curtains: 0, fans: 1, plugs: 0, dimmers: 0 },
    { switches: 0, bells: 0, curtains: 1, fans: 0, plugs: 0, dimmers: 0 },
    { switches: 0, bells: 1, curtains: 0, fans: 0, plugs: 0, dimmers: 0 },
  ],
  [
    { switches: 8, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 0 },
    { switches: 4, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 0 },
    { switches: 4, bells: 0, curtains: 0, fans: 1, plugs: 0, dimmers: 0 },
    { switches: 4, bells: 0, curtains: 0, fans: 0, plugs: 1, dimmers: 0 },
    { switches: 4, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 1 },
    { switches: 4, bells: 0, curtains: 1, fans: 0, plugs: 0, dimmers: 0 },
    { switches: 2, bells: 0, curtains: 0, fans: 1, plugs: 0, dimmers: 0 },
    { switches: 2, bells: 0, curtains: 0, fans: 0, plugs: 1, dimmers: 0 },
    { switches: 2, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 1 },
    { switches: 0, bells: 0, curtains: 2, fans: 0, plugs: 0, dimmers: 0 },
    { switches: 0, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 2 },
  ],
  [
    { switches: 6, bells: 0, curtains: 1, fans: 1, plugs: 0, dimmers: 0 },
    { switches: 6, bells: 0, curtains: 0, fans: 1, plugs: 0, dimmers: 1 },
    { switches: 6, bells: 0, curtains: 1, fans: 0, plugs: 0, dimmers: 1 },
    { switches: 6, bells: 0, curtains: 0, fans: 0, plugs: 1, dimmers: 0 },
    { switches: 6, bells: 0, curtains: 0, fans: 1, plugs: 0, dimmers: 0 },
    { switches: 4, bells: 0, curtains: 0, fans: 2, plugs: 0, dimmers: 0 },
    { switches: 4, bells: 0, curtains: 0, fans: 1, plugs: 0, dimmers: 1 },
    { switches: 4, bells: 0, curtains: 0, fans: 0, plugs: 1, dimmers: 1 },
  ],
  [{ switches: 10, bells: 0, curtains: 0, fans: 0, plugs: 0, dimmers: 0 }],
];
